### ISSUE TITLE
Build of frontend doesn't work on Windows

### ISSUE THREAD

**Issue by Qwby** [dancier/dancer#12]
Maven runs "npm build", which in turn runs the script from the package.json which contains the Unix-specific command "mv" instead of the Windows-specific command "move". This prevents the project to be built on Windows machines.

**Comment by jans510** [comment]
Hi @Qwby. Thanks for pointing it out, we never tried to build it on Windows... We could change the name in the webpack config, but then we would need to take care of all configuration files on our own (https://stackoverflow.com/questions/50780983/how-can-i-rename-index-html-in-a-create-react-app-project and https://create-react-app.dev/docs/available-scripts/) and will loose a lot of benefits from react-create-app. I guess we should think about a different way where we do not need to think about renaming the index.html file on using it in the backend.
